apiVersion: v1
kind: Secret
metadata:
  name: backpack-secrets
  labels: {{ include "backpack.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}
  jwt_secret: {{ .Values.gateway.jwtSecret }}
  postgres_password: {{ .Values.postgres.password }}
